server:
  port: 8085
eureka:
  client:
    register-with-eureka: true  #true because userservice is eureka client and needs to register on service registry
    fetch-registry: true  #true becuase userservice is eureka client and fetch info from service registry
    service-url:
      default-zone: http://localhost:8761/eureka # this is eureka server url , so userService will use this url to get register on eureka server
  instance:
    prefer-ip-address: true     #Default: false Flag to say that, when guessing a hostname, the IP address of the server should be used in preference to the hostname reported by the OS.
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AnchalVaish/microserviceConfiglatest
          clone-on-start: true