server:
  port: 8084
eureka:
  client:
    register-with-eureka: true  #true because userservice is eureka client and needs to register on service registry
    fetch-registry: true  #true becuase userservice is eureka client and fetch info from service registry
    service-url:
      default-zone: http://localhost:8761/eureka # this is eureka server url , so userService will use this url to get register on eureka server
  instance:
    prefer-ip-address: true     #Default: false Flag to say that, when guessing a hostname, the IP address of the server should be used in preference to the hostname reported by the OS.

spring:
  cloud:
    gateway:
      routes:
      - id: USERSERVICE
        uri: lb://USERSERVICE  # lb beacuse laodbalanced ,as we have registered userservice on service registry hence service name direclty in url
        predicates:
        - Path= /users/** 
      - id: HOTELSERVICE
        uri: lb://HOTELSERVICE
        predicates:
        - Path=/hotels/** , /staff/**
      - id: RATINGSERVICE
        uri: lb://RATINGSERVICE
        predicates:
        - Path=/ratings/**
          
          
            