server:
  port: 8083
spring:
  datasource:
    name: jdbc
    url: jdbc:mysql://localhost:3306/jdbc
    username: root
    password: Iphone@10
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true   #this is to show sql logs in console
eureka:
  client:
    register-with-eureka: true  #true because userservice is eureka client and needs to register on service registry
    fetch-registry: true  #true becuase userservice is eureka client and fetch info from service registry
    service-url:
      default-zone: http://localhost:8761/eureka # this is eureka server url , so userService will use this url to get register on eureka server
  instance:
    prefer-ip-address: true     #Default: false Flag to say that, when guessing a hostname, the IP address of the server should be used in preference to the hostname reported by the OS.
